Merlinwebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('merlindjango.urls')),
    path('home/', include('merlindjango.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merlindjango/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'merlindjango'

urlpatterns = [
    # # /news/
    path('news/', views.news, name='news'),
    #
    # # /home
    path('', views.home, name='home'),
    #
    # # /about
    path('about/', views.aboutmerlin, name='about_merlin'),
    #
    # # /description
    path('description/', views.description, name='description'),
    #
    # # /downloads
    path('downloads/', views.downloads, name='downloads'),
    path('downloads/<path>', views.download_version, name='download_version'),
    #
    # # /team
    path('team/', views.team, name='team'),
    #
    # # /tutorial
    path('tutorial/', views.tutorial, name='tutorial'),
    #
    # # /user
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    #
    # # /models
    path('gsm_models/', views.gsmmodels, name='gsm_models'),
    path('form_submit_model/', views.submit_model, name='submit_model'),
    path('delete_model/<int:id_modelo>', views.delete_model, name='delete_model'),
    path('download/<path>', views.download_model, name='download_model'),
    path('form_edit_model/<int:id_modelo>', views.edit_model, name='edit_model'),
    #
    # # /memote
    path('memote/<int:id_modelo>', views.submitMemote, name='submitMemote'),
    path('memote_status/<e_mail>/<int:submissionID>', views.display_results_wrapper, name='memote_status'),
    path('memote_download/<content>', views.display_results_wrapper, name='memote_download')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merlindjango/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Permission, User

# classes
class Noticias(models.Model):
    titulo_noticia = models.CharField(max_length=500)
    imagem_noticia = models.FileField(null=True, blank=True)
    texto = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

    def get_absolute_url(self):
        return reverse('merlindjango:news', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = ("Notícias")
        ordering = ['-created_at', ]

    def submit_noticias_db(self, titulo_noticia, imagem_noticia, texto, created_at):
        self.titulo_noticia = titulo_noticia
        self.imagem_noticia = imagem_noticia
        self.texto = texto
        self.created_at = created_at
        self.save()


class downloadableFiles(models.Model):
    titulo_versao = models.CharField(max_length=500)
    update_ficheiro = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

    class Meta:
        verbose_name_plural = ("Downloads")
        ordering = ['-created_at', ]


class GSMModels(models.Model):
    id_modelo = models.AutoField(primary_key=True)
    name = models.CharField(max_length=500)
    organism = models.CharField(max_length=500)
    publication = models.TextField()
    year = models.IntegerField()
    file = models.FileField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('merlindjango:gsm_models', kwargs={'pk': self.id_modelo})

    class Meta:
        verbose_name_plural = ("GSMModels")

    def getmodel(self, identifier):
        try:
            return GSMModels.objects.get(id_modelo=identifier)
        except Exception as E:
            print(E)
            return None

    def get_model_by_name(self, name):
        return self.objects.get(name=name)

    def get_model_by_year(self, year):
        return self.objects.get(year=year)

    def get_model_by_user(self, user):
        return self.objects.get(user=user)

    def get_model_by_boolean(self):
        return self.objects.get(is_public=True)

    def submit_model_db(self, name, organism, publication, year, file, is_public, user):
        self.name = name
        self.organism = organism
        self.publication = publication
        self.year = year
        self.file = file
        self.is_public = is_public
        self.user = user
        self.save()

    def edit_model_db_name(self, modelID, new_name):
        model = self.getmodel(modelID)
        model.name=new_name
        model.save()

    def edit_model_db_organism(self, modelID, new_organism):
        model = self.getmodel(modelID)
        model.organism=new_organism
        model.save()

    def edit_model_db_publication(self, modelID, new_publication):
        model = self.getmodel(modelID)
        model.publication=new_publication
        model.save()

    def edit_model_db_year(self, modelID, new_year):
        model = self.getmodel(modelID)
        model.year=new_year
        model.save()

    def edit_model_db_file(self, modelID, new_file):
        model = self.getmodel(modelID)
        model.file=new_file
        model.save()

    def edit_model_db_is_public(self, modelID, novo_is_public):
        model = self.getmodel(modelID)
        model.is_public=novo_is_public
        model.save()

    def delete_model(self, modelId):
        model = self.getmodel(modelId)
        model.delete()

    def selection(self,user, id_modelo):
        userID = self.objects.get(user_id=user)
        userID.getmodel(id_modelo)

merlindjango/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import GSMModels


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']


class ModelForm(forms.ModelForm):

    class Meta:
        model = GSMModels
        fields = ['id_modelo', 'name', 'organism', 'publication', 'year', 'file', 'is_public']

merlindjango/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm, ModelForm
from .models import GSMModels, Noticias, downloadableFiles
from django.conf import settings
from django.http import HttpResponse, Http404, HttpResponseForbidden
from itertools import chain
import requests
import os
import shutil


def news(request):
    template_name = 'merlindjango/news.html'
    noticia = Noticias.objects.order_by('-created_at')
    return render(request, template_name, {'noticia': noticia})


def home(request):
    template_name = 'merlindjango/home.html'
    return render(request, template_name)


def aboutmerlin(request):
    template_name = 'merlindjango/about_merlin.html'
    return render(request, template_name)


def description(request):
    template_name = 'merlindjango/description.html'
    return render(request, template_name)


def downloads(request):
    template_name = 'merlindjango/downloads.html'
    download = downloadableFiles.objects.order_by('-created_at')
    return render(request, template_name, {'download': download})


def download_version(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        response = HttpResponse(content_type='force-download')
        response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
        return response
    raise Http404


def team(request):
    template_name = 'merlindjango/team.html'
    return render(request, template_name)


def tutorial(request):
    template_name = 'https://merlin-sysbio.org/tutorial.html'
    return redirect(template_name)


def register(request):
    form = UserForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password, first_name=first_name, last_name=last_name)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'merlindjango/home.html')
    context = {"form": form}
    return render(request, 'merlindjango/register.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                userName = user.first_name
                userId = user.pk
                context = {"userId": userId, "userName": userName}
                return render(request, 'merlindjango/home.html', context)
            else:
                return render(request, 'merlindjango/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'merlindjango/login.html', {'error_message': 'Invalid login'})
    return render(request, 'merlindjango/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {"form": form}
    return render(request, 'merlindjango/home.html', context)


def submit_model(request):
    if request.user.is_authenticated:
        form = ModelForm(request.POST, request.FILES or None)
        if form.is_valid():
            model = form.save(commit=False)
            model.user = request.user
            model.save()
            return gsmmodels(request, True)
        return render(request, 'merlindjango/form_submit_model.html', {'form': form})
    else:
        return render(request, 'merlindjango/login.html')


def delete_model(request, id_modelo):
    if request.user.is_authenticated:
        m = GSMModels()
        modelInDatabase = m.getmodel(id_modelo)
        if modelInDatabase.user == request.user or request.user.is_superuser:
            m.delete_model(id_modelo)
            return gsmmodels(request)
    else:
        return render(request, 'merlindjango/login.html')


def download_model(request, path):
    if request.user.is_authenticated:
        file_path = os.path.join(settings.MEDIA_ROOT, path)
        if os.path.exists(file_path):
            response = HttpResponse(content_type='force-download')
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
        raise Http404
    else:
        return render(request, 'merlindjango/login.html')


def edit_model(request, id_modelo):
    if request.user.is_authenticated:
        m = GSMModels()
        modelindb = m.getmodel(id_modelo)
        if modelindb.user == request.user or request.user.is_superuser:
            form = ModelForm(request.POST, request.FILES or None, instance=modelindb)
            if form.is_valid():
                model = form.save(commit=False)
                model.save()
                return gsmmodels(request)
            return render(request, 'merlindjango/form_edit_model.html', {'form': form})
        else:
            return HttpResponseForbidden("")
    else:
        return render(request, 'merlindjango/login.html')


def gsmmodels(request, submitted=False):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            template_name = 'merlindjango/gsm_models.html'
            model = GSMModels.objects.all()
            return render(request, template_name, {'model': model, "submittedHTML": submitted})
        else:
            template_name = 'merlindjango/gsm_models.html'
            i = GSMModels.objects.filter(user=request.user)
            j = GSMModels.objects.filter(is_public=True)
            model = list(set(chain(i, j)))
            return render(request, template_name, {'model': model, "submittedHTML": submitted})
    else:
        return render(request, 'merlindjango/login.html')


def submitMemote(request, id_modelo):

    if request.user.is_authenticated:

        model_path = os.path.join(settings.MEDIA_ROOT, GSMModels.objects.filter(pk=id_modelo)[0].file.name)
        new_model_path = os.path.join(settings.MEDIA_ROOT, 'temp_model')
        new_model_path_2 = os.path.join(new_model_path, 'model.xml')

        if os.path.exists(new_model_path):
            shutil.rmtree(new_model_path, ignore_errors=True)

        os.mkdir(new_model_path)
        shutil.copy(model_path, new_model_path_2)

        e_mail = request.user.email
        data_auth_path = os.path.join(settings.MEDIA_ROOT, 'data_authorization.txt')

        data_auth_file = open(new_model_path_2, 'rb')
        model_file = open(data_auth_path, 'rb')
        files = [('files', data_auth_file),
                 ('files', model_file)]
        try:
            r = requests.post('http://palsson.di.uminho.pt:6082/submitMerlinPlugin/Memote/' + e_mail, files=files)
            data_auth_file.close()
            model_file.close()
        except:

            data_auth_file.close()
            model_file.close()

            if os.path.exists(new_model_path):
                shutil.rmtree(new_model_path, ignore_errors=True)

            return render(request, 'merlindjango/memote_fail.html')

        if r.status_code == 201:
            submissionID = eval(r.text).get('submissionID')

            if os.path.exists(new_model_path):
                shutil.rmtree(new_model_path, ignore_errors=True)

            return display_results_wrapper(request, e_mail, int(submissionID))
        else:

            if os.path.exists(new_model_path):
                shutil.rmtree(new_model_path, ignore_errors=True)

            return render(request, 'merlindjango/memote_fail.html')

    else:
        return render(request, 'merlindjango/login.html')


def display_results_wrapper(request, e_mail, submissionID):

    if request.user.is_authenticated:

        try:
            r = requests.get('http://palsson.di.uminho.pt:6082/status/' + str(e_mail) + '/' + str(submissionID))
        except:
            return render(request, 'merlindjango/memote_fail.html')

        ok_status_code = [202, 201]

        if r.status_code == 200:
            context = {'content': 'http://palsson.di.uminho.pt:6082/download/' + str(e_mail) + '/' + str(submissionID)}
            return render(request, 'merlindjango/submission_download.html', context)

        elif r.status_code in ok_status_code:
            return render(request, 'merlindjango/status.html', {'email': e_mail, 'submissionID': submissionID})

        else:
            return render(request, 'merlindjango/memote_fail.html')

    else:
        return render(request, 'merlindjango/login.html')

merlindjango/templates/merlindjango/delete_gsm_model.html
{%  if statusInHtml %}
Deleted Model with ID {{ model }} successfully ?
{%  else %}
Something went wrong
{%  endif%}

merlindjango/templates/merlindjango/detail.html
{% extends 'merlindjango/navbar.html' %}
{% block title %}Noticias{% endblock %}

{% block body %}
    <img src="{{ noticias.imagem_noticia }}" alt="">

    <h1>{{ noticias.titulo_noticia }}</h1>
    <h3>{{ noticias.autor }}</h3>

    <ul>
        {% for news in noticias.todas_noticias_set.all %}
            <li>{{ news.sub_titulo }} - {{ news.tipo_ficheiro }}</li>
        {% endfor %}
    </ul>
{% include 'merlindjango/footer.html' %}

{% endblock %}

merlindjango/templates/merlindjango/footer.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />


<div class="footer" style="padding: 10px">
    <div class= "footer footer-bottom" style=" opacity: 1; border-radius: 0; background-color: aliceblue">
        <div class="footer-text" style="margin-top: auto">
            Copyright © 2018 <i>merlin</i>. All Rights Reserved.
        </div>
    </div>
</div>

merlindjango/templates/merlindjango/form_edit_model.html
{% extends 'merlindjango/navbar.html' %}
{% block title %}Edit Model{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Edit Model</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'merlindjango/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'merlindjango/footer.html' %}

{% endblock %}

merlindjango/templates/merlindjango/form_submit_model.html
{% extends 'merlindjango/navbar.html' %}
{% block title %}Add a New Model{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Model</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'merlindjango/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'merlindjango/footer.html' %}

{% endblock %}

merlindjango/templates/merlindjango/gsm_models.html
<!DOCTYPE html>
{% extends 'merlindjango/navbar.html' %}
{% load static %}
{% block gsmmodels_active %}active{% endblock %}
<link rel="stylesheet" href="../../static/merlindjango/css/table.css"/>


{% block body %}

    <div style="max-width: 62%; margin: auto">
        <h1 style="text-align: center"><b>Models Repository</b></h1>
        <hr>
        <a  href="{% url 'merlindjango:submit_model' %}" class="btn btn-primary btm-sm" style="background-color: cornflowerblue; border: 0"> Submit Model </a>
        <hr>
        {% if submittedHTML %}
        <p>Model submitted successfully!</p>
        {% elif delete_model %}
        <p>Model deleted successfully!</p>
        {% endif %}

        <table class="table" style="width: 100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Organism</th>
                    <th>Publication</th>
                    <th>Year</th>
                    <th>Public</th>
                    <th>File</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for models in model %}
                <tr>
                    <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:80px;">{{ models.name}} &nbsp;</td>
                    <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">{{ models.organism}} &nbsp;</td>
                    <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">{{ models.publication}} &nbsp;</td>
                    <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:40px;">{{ models.year}} &nbsp;</td>
                    <td>{{ models.is_public }}</td>
                    <td><a  href="{{ models.file.url }}" class="btn btn-primary btm-sm" target="_blank" style="background-color: darkcyan; border: 0" download> Download </a> </td>
                    <td><a  href="{% url 'merlindjango:submitMemote' models.id_modelo %}" class="btn btn-primary btm-sm" target="_blank" style="background-color: #2a7bb8; border: 0"> Memote </a> </td>
                    {% if request.user == models.user or request.user.is_superuser%}
                    <td><a href="{% url 'merlindjango:delete_model' models.id_modelo %}" class="btn btn-primary btm-sm" style="background-color: darkred; border: 0" onclick="return confirm('Are you sure you want to delete this model?')"> Delete </a> </td>
                    <td><a  href="{% url 'merlindjango:edit_model' models.id_modelo %}" class="btn btn-primary btm-sm" style="background-color:coral; border: 0"> Edit </a> </td>
                    {% endif %}
                    {% if request.user != models.user %}
                    <td></td>
                    <td></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% include 'merlindjango/footer.html' %}
{% endblock %}

merlindjango/templates/merlindjango/home.html
<!DOCTYPE html>
{% extends 'merlindjango/navbar.html' %}
{% load static %}
{% block home_active %}active{% endblock %}


{% block body %}

    {% if userId %}
    <h1>Welcome {{ userName }}</h1>
    {%   endif%}
    <div style="max-width: 62%; margin: auto">
        <h1 style="text-align: center"><b>Home</b></h1>
        <hr>
        <div style="text-align: center">
            <img src="{% static "images/Merlin.png" %}" alt="Merlin" width="55%" height="100%">
        </div>
        <br>
        <h2>Latest News</h2>
        <h3>S2M2 - Summer School in Metabolic Modeling (29 June - 3 July 2020) - 2nd Edition!!!</h3>
        <p>
            BioSystems group is organizing for the second time a 5-day course on metabolic modelling – Summer School in Metabolic Modeling. The course will cover the full process from model reconstruction to phenotype prediction using genome-scale metabolic models.
            <br>
            The focus of this course will be on user-friendly tools for genome-scale metabolic model reconstruction (<i>merlin</i>) and simulation (<i>Optflux</i>) as to introduce alternatives to improve those models with omics data integration.
            <br>
            See more at <a rel="nofollow" class="external free" href="http://s2m2.bio.di.uminho.pt/">http://s2m2.bio.di.uminho.pt/
            </a>
        </p>
        <br>
        <img src="{% static "images/S2m2_2020.png "%}" alt="S2m2 2020" width="90%" height="90%">
        <br>
        <h3>A new tutorial is available for <i>merlin</i></h3>
        <p>
            We have implemented an extensive hands-on tutorial for <i>merlin</i>, which follows every step towards the reconstruction of a genome-scale metabolic model.
            <br>
            To access it, please click on the tutorial section on this website's upper navigation bar.
        </p>
        <br>
        <h2><i>merlin</i></h2>
        <p>
            <i>merlin</i> is a simple, graphical and user-oriented solution for the reconstruction of genome-scale metabolic models.
        </p>
        <p>
            It will guide you along the model reconstruction, providing several tools that help to improve and curate the model throughout the whole process.
        </p>
        <img alt="Reconstruction" src="{% static "images/1200px-Reconstruction.png" %}" width="800" height="450">
        <br>
        <h2>Ongoing work</h2>
        <p>
            We are currently working on the following features and will release a new version of <i><b>merlin</b></i> in the near future:
        </p>
        <ul>
            <li> Integration of <i>modelSEED</i> metabolic data.</li>
            <li> Integration of <i>BIGG</i> metabolic data.</li>
            <li> Development of a plugin towards the integration of regulatory data.</li>
        </ul>
        <br>
        <h2>Getting Started</h2>
        <ul>
            <li> <a rel="nofollow" class="external text" href="{% url "merlindjango:tutorial" %}">How to use merlin</a></li>
            <li> <a rel="nofollow" class="external text" href="{% url "merlindjango:downloads" %}">Downloading merlin</a></li>
        </ul>
        <br>
    </div>
{% include 'merlindjango/footer.html' %}

{% endblock %}

merlindjango/templates/merlindjango/register.html
<!DOCTYPE html>
{% extends 'merlindjango/navbar.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'merlindjango/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'merlindjango:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'merlindjango/footer.html' %}

{% endblock %}

merlindjango/templates/merlindjango/status.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta http-equiv="refresh" content="10;url={% url 'merlindjango:memote_status' email submissionID %}">
    <title>merlin</title>
{#    <link rel="stylesheet" href="{{ url_for('static', filename='css/center.css') }}">#}
{#    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}">#}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Oxygen&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>


<body>

<div class="center" align="center" style="border: 0">
    <h1 style="color: #34495e"><b><i>merlin</i> GSM model <i>MEMOTE</i></b></h1>
    <br>
    <br>
{#    <img src="{{ url_for('static', filename = 'images/biocoiso.gif') }}" alt="BioISO" height="325px">    <br>#}
    <br>
    <h3><b>Status report</b></h3>
    <p>Submission ID: {{submissionID}}</p> <br>
{#    {% if status["queue"] %}#}
{#        <h3>{{status["queue"]}}</h3>#}
{#    {% endif %}#}
{#    {% if status["message"] %}#}
{#        <h3>{{status["message"]}}</h3>#}
{#    {% endif %}#}
    <br>
	<h3>This page refreshes automatically, 10 seconds at a time. Please wait for your download to be ready!</h3>
    <h3>Otherwise, you can consult your results later in the home page. For that, you must keep the submission ID and e-mail provided at the time of the submission.</h3>
</div>

{#<div class="footer">#}
{##}
{#    <table>#}
{#        <tr>#}
{#            <th><a href="{{url_for('index')}}">BioISO 2019</a> <br>#}
{#                by <a href="https://www.ceb.uminho.pt/People/Profile/fernandocruz" target="_blank">Fernando Cruz</a>,#}
{#                <a href="https://www.ceb.uminho.pt/People/Profile/davidelagoa" target="_blank">Davide Lagoa</a>, <br>#}
{#                <a href="https://www.ceb.uminho.pt/People/Profile/joaoribeiro" target="_blank">João Capela</a> and#}
{#                <a href="https://www.ceb.uminho.pt/People/Profile/odias" target="_blank">Oscar Dias</a>#}
{#            </th>#}
{#            <th><a href="https://www.eng.uminho.pt/en" target="_blank"> <img border="0" alt="School of Engineering" src="{{ url_for('static', filename = 'images/EENG.jpg') }}"></a></th>#}
{#            <th><a href="https://www.ceb.uminho.pt/" target="_blank"> <img border="0" alt="Centre of Biological Engineering" src="{{ url_for('static', filename = 'images/ceb1.png') }}"></a></th>#}
{#            <th><a href="https://www.elixir-portugal.org/" target="_blank"> <img border="0" alt="BioData" src="{{ url_for('static', filename = 'images/biodata_elixir.png') }}"></a></th>#}
{#        </tr>#}
{#    </table>#}

{#</div>#}

</body>
</html>